# Enhanced Dependency Review Action

# This Action performs a comprehensive scan on the dependency manifest files that are modified as part of a Pull Request. It identifies and reports any known-vulnerable versions of the packages that are declared or updated in the PR. Once this Action is installed and the workflow run is marked as required, it prevents PRs that introduce known-vulnerable packages from being merged.

# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

name: 'Enhanced Dependency Review'
on: 
  pull_request:
    types: [opened, synchronize, reopened]

permissions: 
  contents: write

jobs:
  dependency-review:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ios-latest, android-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Perform Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Report Vulnerabilities'
        run: |
          if [[ -n "${{ steps.dependency-review.outputs.vulnerabilities }}" ]]; then
            echo "Vulnerabilities found in dependencies:"
            echo "${{ steps.dependency-review.outputs.vulnerabilities }}"
            exit 1
          fi
        shell: bash