name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest, windows-latest, macos-latest, andriod-latest, ios-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365
      uses: docker/setup-buildx-action@v2.9.0
      with:
        # Buildx version. (eg. v0.3.0)
        version: # optional
        # Sets the builder driver to be used
        driver: # optional, default is docker-container
        # List of additional driver-specific options. (eg. image=moby/buildkit:master)
        driver-opts: # optional
        # Flags for buildkitd daemon
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        # Sets up docker build command as an alias to docker buildx build
        install: true
        # Switch to this builder instance
        use: # optional, default is true
        # Optional address for docker socket or context from `docker context ls`
        endpoint: # optional
        # Fixed platforms for current node. If not empty, values take priority over the detected ones
        platforms: # optional
        # BuildKit config file
        config: # optional
        # Inline BuildKit confige
        config-inline: # optional
        # Append additional nodes to the builder
        append: # optional
        # Cleanup temp files and remove builder at the end of a job
        cleanup: # optional, default is true
